# 监控系统配置示例文件
# 复制此文件为 config.yaml 并根据实际情况修改

# 数据库配置
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: evm_tracker

# 通知配置
notifications:
  # 邮件通知
  email:
    enabled: true
    smtp_server: smtp.qq.com
    smtp_port: 465
    username: fangfeng335@qq.com
    password: xuyomfhnxenlbggj
    sender: fangfeng335@qq.com
    recipients:
      - fangfeng335@qq.com
      - 250969751@qq.com
  
  # Telegram通知
  telegram:
    enabled: true
    token: "7638015275:AAGuzFYTwgiihQ5iIrYXNJA-JE1ZPvGPWr4"
    chat_ids:
      - 2006080530
      - -1002615732272

# 服务检查配置
service_checks:
  enabled: true
  interval_minutes: 5  # 默认检查间隔时间（分钟）
  endpoints:
    - name: "EVM_tracker后台服务"
      url: "http://localhost:3001/health"
      expected_status: 200
      expected_content: '"status":"ok"'
      headers:
        Content-Type: "application/json"
      interval_minutes: 0.2  # 每5分钟检查一次
  
    - name: "Ankr Token是否能用"
      url: "https://rpc.ankr.com/multichain/498c84e3e1b62890931577d9a7a5eb46b4af57a32bb903ff2b1bb9401d8d77aa"
      method: "POST"
      expected_status: 200
      expected_content: '"blockchain":"eth"'  # 简单字符串匹配作为备用检查
      headers:
        Content-Type: "application/json"
      interval_minutes: 60  # 每60分钟（1小时）检查一次
      json_check:
        path: "result.stats[0].blockchain"
        expected_value: "eth"
      body: |
        {
          "jsonrpc": "2.0",
          "method": "ankr_getBlockchainStats",
          "params": {
            "blockchain": "eth"
          },
          "id": 1
        }

# 系统资源监控配置
system_monitoring:
  enabled: true
  interval_minutes: 5
  thresholds:
    cpu_percent: 80.0
    memory_percent: 80.0
    disk_percent: 85.0 