# 监控系统配置示例文件
# 复制此文件为 config.yaml 并根据实际情况修改

# 数据库配置
database:
  host: localhost
  port: 5432
  user: postgres
  password: yourpassword
  dbname: yourdbname

# 通知配置
notifications:
  # 邮件通知
  email:
    enabled: true
    smtp_server: smtp.qq.com
    smtp_port: 465
    username: youremail@example.com
    password: yourpassword
    sender: thesendmail@example.com
    recipients:
      - recevie1@example.com
      - recevie2@example.com
  
  # Telegram通知
  telegram:
    enabled: true
    token: "your_telegram_bot_token"
    chat_ids:
      - chat_ids
      - channel_id

# 服务检查配置
service_checks:
  enabled: true
  interval_minutes: 5  # 默认检查间隔时间（分钟）
  endpoints:
    - name: "EVM_tracker后台服务"
      url: "http://localhost:3001/health"
      expected_status: 200
      expected_content: '"status":"ok"'
      headers:
        Content-Type: "application/json"
      interval_minutes: 5  # 每5分钟检查一次
  
    - name: "Ankr Token是否能用"
      url: "https://rpc.ankr.com/multichain/api-token"
      method: "POST"
      expected_status: 200
      expected_content: '"blockchain":"eth"'  # 简单字符串匹配作为备用检查
      headers:
        Content-Type: "application/json"
      interval_minutes: 60  # 每60分钟（1小时）检查一次
      json_check:
        path: "result.stats[0].blockchain"
        expected_value: "eth"
      body: |
        {
          "jsonrpc": "2.0",
          "method": "ankr_getBlockchainStats",
          "params": {
            "blockchain": "eth"
          },
          "id": 1
        }

# 系统资源监控配置
system_monitoring:
  enabled: true
  interval_minutes: 5
  thresholds:
    cpu_percent: 80.0
    memory_percent: 80.0
    disk_percent: 85.0 
