general:
  app_name: web服务监控与通知系统
  check_interval: '60'
  logging_level: info
notifications:
  email:
    password: xuyomfhnxenlbggj
    recipients: 'fangfeng335@qq.com

      250969751@qq.com'
    sender: fangfeng335@qq.com
    smtp_port: '587'
    smtp_server: smtp.qq.com
    use_tls: 'on'
    username: fangfeng335@qq.com
  email_enabled: 'on'
  format: text
  notify_on_status: error
  telegram:
    chat_ids: '2006080530'
    token: 7638015275:AAGuzFYTwgiihQ5iIrYXNJA-JE1ZPvGPWr4
  telegram_enabled: 'on'
service_checks:
  enabled: true
  endpoints:
  - body: null
    enabled: true
    expected_content: '"status":"ok"'
    expected_status: 200
    headers:
      Content-Type: application/json
    id: EVM_tracker后台服务
    interval_minutes: 10
    json_check: null
    method: GET
    name: EVM_tracker后台服务
    url: http://localhost:3001/health
  - body: "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"ankr_getBlockchainStats\",\n\
      \  \"params\": {\n    \"blockchain\": \"eth\"\n  },\n  \"id\": 1\n}\n"
    expected_content: '"blockchain":"eth"'
    expected_status: 200
    headers:
      Content-Type: application/json
    id: Ankr Token是否能用
    interval_minutes: 60
    json_check:
      expected_value: eth
      path: result.stats[0].blockchain
    method: POST
    name: Ankr Token是否能用
    url: https://rpc.ankr.com/multichain/498c84e3e1b62890931577d9a7a5eb46b4af57a32bb903ff2b1bb9401d8d77aa
  - body: null
    enabled: true
    expected_content: null
    expected_status: 200
    headers: null
    id: test
    interval_minutes: 10
    json_check: null
    method: GET
    name: test2
    url: http://127.0.0.1:3003/config/#endpointSettings
  interval_minutes: 5
